#!/usr/bin/env python
# -*- coding: utf-8 -*-

import optparse
import os
import re

from models import tit

def list(command, options, _tit):
    """Lists todo items 
Usage: tit list [list/all]
    tit list                    -- displays the current todo list
    tit list [list]        -- displays the todo list items in this list
    tit list all                -- displays all items in all lists
    tit list help               -- displays this helpful text"""

    if command['list'] and not command['list'] == 'all':
        if command['list'].isdigit():
            print format_output(_tit.find(id=command['list']).list())
        else:
            print format_output(_tit.find(name=command['list']).list())
    elif command['list'] and command['list'] == 'all':
        print format_output(_tit.list())
    else:
        print format_output(_tit.current_list.list())

def add(command, options, _tit):
    """Creates a new item or list
Usage: tit add [list] [item]
    tit add [item]           -- creates a new item
    tit add [list] [item]    -- creates a new item in the list list
    tit add list [list]      -- creates a new list
    tit add help             -- dislpays this helpful text"""

    if command['item'] and not 'list' in command.keys():
        _tit.current_list.add(new_name=command['item'])
        _tit.save()
    elif command['list'] == 'list' and command['item']:
        _tit.add(new_name=command['item'])
        _tit.save()
    elif command['item'] and command['list']:
        if command['list'].isdigit():
            _tit.find(id=command['list']).add(new_name=command['item'])
        else:
            _tit.find(name=command['list']).add(new_name=command['item'])

        _tit.save()

def rm(command, options, _tit):
    """Removes an item or list
Usage: tit rm [list] [item]
    tit rm [item]           -- removes an item
    tit rm [list] [item]    -- removes and item from the list
    tit rm list [list]      -- removes a list
    tit rm help             -- displays this helpful text"""

    if command['item'] and not 'list' in command.keys():
        if command['item'].isdigit():
            _tit.current_list.rm(rm_id=command['item'])
        else:
            _tit.current_list.rm(rm_name=command['item'])
        _tit.current_list.list()
        _tit.save()
    elif command['list'] == 'list' and command['item']:
        if command['item'].isdigit():
            _tit.rm(rm_id=command['item'])
        else:
            _tit.rm(rm_name=command['item'])
        _tit.list()
        _tit.save()
    elif command['item'] and command['list']:
        l = None
        i = None

        if command['list'].isdigit():
            l = _tit.find(id=command['list'])
        else:
            l = _tit.find(name=command['list'])

        if command['item'].isdigit():
            i = l.find(id=command['item'])
        else:
            i = l.find(name=command['item'])

        l.rm(rm_item=i)
        l.list()
        _tit.save()

def switch(command, options, _tit):
    """Switches the current todo lists
Usage: tit switch [list]
    tit switch [list]    -- switches to the list
    tit switch help      -- displays this helpful text"""
    if command['list'].isdigit():
        _tit.current_list = _tit.find(id=command['list'])
    else:
        _tit.current_list = _tit.find(name=command['list'])

    if _tit.current_list is None:
        print 'Error finding list'
        return

    _tit.current_list.list()
    _tit.save()

_usage = u"""usage: %prog [command]
In this case command can be any of these commands:
    list - lists todo-items in the current list
    add - adds todo-items and lists
    rm - removes todo-items and lists
    switch - switches the current list to another list

For more information about the commands type '%prog [command] help'"""
_version = "%prog 0.0.1"

_commands = {
    # Tit commands
    'list': {
        'min_arg_count': 0,
        'args': ['list'],
        'function': list,
    },
    'add': {
        'min_arg_count': 1,
        'args': ['[list]', 'item', '[priority]'],
        'function': add,
    },
    'rm': {
        'min_arg_count': 1,
        'args': ['[list]', 'item'],
        'function': rm,
    },
    'start': {
        'min_arg_count': 1,
        'args': ['[list]', 'item'],
    },
    'fin': {
        'min_arg_count': 1,
        'args': ['[list]', 'item']
    },
    'pause': {
        'min_arg_count': 1,
        'args': ['[list]', 'item']
    },
    'switch': {
        'min_arg_count': 1,
        'args': ['list'],
        'function': switch
    },
}

_todo_lists_file = '%s/.tit/todo_lists' % os.getenv('HOME')

_re_arg_is_optional = re.compile(r"^\[.*\]$")

_terminal_colors = {
    'black': 30,
    'red': 31,
    'green': 32,
    'yellow': 33,
    'blue': 34,
    'magenta': 35,
    'cyan': 36,
    'white': 37,
}

_formatting = {
    '$CLEAR': '\033[0m',
    '$INFO': '\033[1;%dm' % _terminal_colors['yellow'],
    '$ID': '\033[1;%dm' % _terminal_colors['cyan'],
    '$LIST': '\033[1;%dm\033[1;4m' % _terminal_colors['green'],
    '$0ITEM': '\033[1;%dm' % _terminal_colors['green'],
    '$1ITEM': '\033[1;%dm' % _terminal_colors['green'],
    '$2ITEM': '\033[1;%dm' % _terminal_colors['white'],
    '$3ITEM': '\033[1;%dm' % _terminal_colors['yellow'],
    '$4ITEM': '\033[1;%dm' % _terminal_colors['yellow'],
    '$5ITEM': '\033[1;%dm' % _terminal_colors['red'],
    '$ITEM': '\033[1;4m',
}

def format_output(string):
    for key in _formatting.keys():
        string = string.replace(key, _formatting[key])

    return string

def main():
    (command, options) = get_arguments()

    if command is None and options is None:
        return

    if False and options['file']:    # Change this when I figure out why options['file'] throws an AttributeError
        _tit = tit.load(options['file'])
    else:
        _tit = tit.load()

    # create ~/.tit if it doesn't exists
    # also create ~/.tit/todo_lists
    # read ~/.tit/current to see what list is currently in use

    arguments = (command, options, _tit)
    if 'function' in command.keys():
        command['function'](*arguments)
    else:
        print 'This this not implemented'

def get_arguments():
    parser = optparse.OptionParser(usage=_usage, version=_version)
    parser.add_option("-m", "--message", dest="message", help="Commit message")
    parser.add_option("-f", "--file", dest="file", help="xml data file")

    (options, args) = parser.parse_args()

    if not len(args) > 0:
        parser.print_help()
        return None, None
    if not args[0] in _commands.keys():
        parser.print_help()
        return None, None

    command = {
        'command': args[0],
        'function': _commands[args[0]]['function'],
    }

    if len(args) > 1 and args[1] == 'help':
        print command['function'].__doc__
        return None, None

    if not len(args) >= _commands[args[0]]['min_arg_count']+1:
        print command['function'].__doc__
        return None, None

    args_offset = 1
    for i, arg in enumerate(_commands[args[0]]['args']):
        if _re_arg_is_optional.match(arg) is not None and len(args) - 1 < len(_commands[args[0]]['args']):
            args_offset -= 1
            continue

        try:
            command[arg.replace('[', '').replace(']', '')] = args[args_offset+i]
        except:
            command[arg] = None

    return command, options

if __name__ == '__main__':
    main()

