#!/usr/bin/env python
# -*- coding: utf-8 -*-

import optparse
import os
import re

from models import tit

def list(command, options, _tit):
    """Lists todo items 
Usage: tit list [list/all]
    tit list                    -- displays the current todo list
    tit list [list]        -- displays the todo list items in this list
    tit list all                -- displays all items in all lists
    tit list help               -- displays this helpful text"""

    if command['list'] and not command['list'] == 'all':
        if command['list'].isdigit():
            print format_output(_tit.find(id=command['list']).list())
        else:
            print format_output(_tit.find(name=command['list']).list())
    elif command['list'] and command['list'] == 'all':
        print format_output(_tit.list())
    else:
        print format_output(_tit.current_list.list())

def add(command, options, _tit):
    """Creates a new item or list
Usage: tit add [type] [name] [priority/description/text]
    tit add item [name] [priority]      -- creates a new item
    tit add list [name] [description]   -- creates a new list
    tit add comment [item] [text]       -- adds a comment to an item
    tit add help                        -- dislpays this helpful text"""

    if command['type'] == 'item':
        if 'priority' in command.keys():
            _tit.current_list.add(new_name=command['name'], new_priority=command['priority'])
        else:
            _tit.current_list.add(new_name=command['name'])

        print 'New item saved'
    elif command['type'] == 'list':
        if 'priority' in command.keys():
            _tit.add(new_name=command['name'], new_description=command['priority'])
        else:
            _tit.add(new_name=command['name'])

        print 'New list saved'
    elif command['type'] == 'comment':
        i = None

        if command['name'].isdigit():
            i = _tit.current_list.find(id=int(command['name']))
        else:
            i = _tit.current_list.find(name=command['name'])

        i.add(new_text=command['priority'])

        print 'New comment saved'

    _tit.save()

def rm(command, options, _tit):
    """Removes an item or list
Usage: tit rm [type] [item] [subitem]
    tit rm item [item]                -- removes an item from the current list
    tit rm comment [item] [comment]   -- removes a comment from an item
    tit rm list [list]                -- removes a list
    tit rm help                       -- displays this helpful text"""

    # tit rm item [item]
    if command['type'] == 'item':
        if command['item'].isdigit():
            _tit.current_list.rm(rm_id=int(command['item']))
        else:
            _tit.current_list.rm(rm_id=int(command['item']))
    # tit rm comment [item] [comment]
    elif command['type'] == 'comment':
        i = None
        if command['item'].isdigit():
            i = _tit.current_list.find(id=int(command['item']))
        else:
            i = _tit.current_list.find(name=command['item'])

        if command['subitem'].isdigit() and i:
            i.rm(rm_id=int(command['subitem']))
        elif i:
            i.rm(rm_text=command['subitem'])
    # tit rm list [list]
    elif command['type'] == 'list':
        if command['item'].isdigit():
            _tit.rm(rm_id=int(command['item']))
        else:
            _tit.rm(rm_name=command['item'])

    _tit.save()

def switch(command, options, _tit):
    """Switches the current todo lists
Usage: tit switch [list]
    tit switch [list]    -- switches to the list
    tit switch help      -- displays this helpful text"""
    if command['list'].isdigit():
        _tit.current_list = _tit.find(id=command['list'])
    else:
        _tit.current_list = _tit.find(name=command['list'])

    if _tit.current_list is None:
        print 'Error finding list'
        return

    print format_output(_tit.current_list.list())
    _tit.save()

_usage = u"""usage: %prog [command]
In this case command can be any of these commands:
    list - lists todo-items in the current list
    add - adds todo-items and lists
    rm - removes todo-items and lists
    switch - switches the current list to another list

For more information about the commands type '%prog [command] help'"""
_version = "%prog 0.0.1"

_commands = {
    # Tit commands
    'list': {
        'min_arg_count': 0,
        'args': ['list'],
        'function': list,
        'alias': 'ls',
    },
    'add': {
        'min_arg_count': 2,
        'args': ['type', 'name', '[priority]'],
        'function': add,
    },
    'remove': {
        'min_arg_count': 2,
        'args': ['type', 'item', '[subitem]'],
        'function': rm,
        'alias': 'rm',
    },
    'change': {
        'min_arg_count': 3,
        'args': ['type', 'item', '[subitem]', '[value]'],
    },
    'start': {
        'min_arg_count': 1,
        'args': ['item'],
    },
    'finish': {
        'min_arg_count': 1,
        'args': ['item'],
        'alias': 'fin',
    },
    'pause': {
        'min_arg_count': 1,
        'args': ['item'],
    },
    'switch': {
        'min_arg_count': 1,
        'args': ['list'],
        'function': switch,
        'alias': 'sw',
    },
}

_todo_lists_file = '%s/.tit/todo_lists' % os.getenv('HOME')

_re_arg_is_optional = re.compile(r"^\[.*\]$")

_term_col = {
    'black': 30,
    'red': 31,
    'green': 32,
    'yellow': 33,
    'blue': 34,
    'magenta': 35,
    'cyan': 36,
    'white': 37,
}

_formatting = {
    '$CLEAR': '\033[0m',
    '$INFO': '\033[1;%dm' % _term_col['yellow'],
    '$ID': '\033[1;%dm' % _term_col['cyan'],
    '$LIST': '\033[1;%dm\033[1;4m' % _term_col['green'],
    '$0ITEM': '\033[1;%dm' % _term_col['green'],
    '$1ITEM': '\033[1;%dm' % _term_col['green'],
    '$2ITEM': '\033[1;%dm' % _term_col['white'],
    '$3ITEM': '\033[1;%dm' % _term_col['yellow'],
    '$4ITEM': '\033[1;%dm' % _term_col['yellow'],
    '$5ITEM': '\033[1;%dm' % _term_col['red'],
    '$ITEM': '\033[1;4m',
}

def format_output(string):
    for key in _formatting.keys():
        string = string.replace(key, _formatting[key])

    return string

def main():
    (command, options) = get_arguments()

    if command is None and options is None:
        return

    if False and options['file']:    # Change this when I figure out why options['file'] throws an AttributeError
        _tit = tit.load(options['file'])
    else:
        _tit = tit.load()

    # create ~/.tit if it doesn't exists
    # also create ~/.tit/todo_lists
    # read ~/.tit/current to see what list is currently in use

    arguments = (command, options, _tit)
    if 'function' in command.keys():
        command['function'](*arguments)
    else:
        print 'This this not implemented'

def get_arguments():
    parser = optparse.OptionParser(usage=_usage, version=_version)
    parser.add_option("-m", "--message", dest="message", help="Commit message")
    parser.add_option("-f", "--file", dest="file", help="xml data file")

    (options, args) = parser.parse_args()

    if not len(args) > 0:
        parser.print_help()
        return None, None

    cmd = None

    for c in _commands.keys():
        if 'alias' in _commands[c].keys() and \
            args[0] == _commands[c]['alias']:
            cmd = c

    if not cmd and not args[0] in _commands.keys():
        parser.print_help()
        return None, None
    elif not cmd:
        cmd = args[0]

    command = {
        'command': cmd,
        'function': _commands[cmd]['function']
    }

    if len(args) > 1 and args[1] == 'help':
        print command['function'].__doc__
        return None, None

    if not len(args) >= _commands[cmd]['min_arg_count']+1:
        print command['function'].__doc__
        return None, None

    args_offset = 1
    for i, arg in enumerate(_commands[cmd]['args']):
        if _re_arg_is_optional.match(arg) is not None and len(args) - 1 < len(_commands[cmd]['args']):
            args_offset -= 1
            continue

        try:
            command[arg.replace('[', '').replace(']', '')] = args[args_offset+i]
        except:
            command[arg] = None

    return command, options

if __name__ == '__main__':
    main()
